[server]
address = "0.0.0.0"
headless=true # This will eliminate automatically open browser
enableCORS=false 
enableXsrfProtection=false 
enableWebsocketCompression=false
enableStaticServing = false

[browser] # This ip and port will show in command prompt
#serverAddress = " "
serverPort = 8501
gatherUsageStats = false

[theme]
base="dark"
font="sans serif"


